// Code generated by wsdl2go. DO NOT EDIT.

package basichttpbinding_ipublicservices

import (
	"reflect"

	"github.com/YapealAG/wsdl2go/soap"
)

// Namespace was auto-generated from WSDL.
var Namespace = "http://www.uid.admin.ch/xmlns/uid-wse"

// UsedNameSpaceMap was auto-generated from WSDL.
var UsedNamespaces = map[string]string{
	"tns9": "http://www.ech.ch/xmlns/eCH-0010/7",
	"tns8": "http://www.ech.ch/xmlns/eCH-0044/4",
	"tns1": "http://www.uid.admin.ch/xmlns/uid-wse-shared/2",
	"tns5": "http://www.ech.ch/xmlns/eCH-0007/6",
	"tns3": "http://www.uid.admin.ch/xmlns/uid-wse/5",
	"tns4": "http://www.ech.ch/xmlns/eCH-0098/5",
	"tns7": "http://www.ech.ch/xmlns/eCH-0116/4",
	"tns2": "http://www.ech.ch/xmlns/eCH-0097/5",
	"tns6": "http://www.ech.ch/xmlns/eCH-0046/5",
	"tns0": "http://www.ech.ch/xmlns/eCH-0108/5",
}

// NewIPublicServices creates an initializes a IPublicServices.
func NewIPublicServices(cli *soap.Client) IPublicServices {
	return &iPublicServices{cli}
}

// IPublicServices was auto-generated from WSDL
// and defines interface for the remote service. Useful for testing.
type IPublicServices interface {
	// <summary>             Get the core data (Kernmerkmale) of a
	// UID entity by its UID              </summary>
	// <param name="uid">UID of requested UID entity</param>
	//
	//	<returns>The requested UID entity</returns>
	GetByUID(GetByUID *GetByUID) (*GetByUIDResponse, error)

	// <summary>             Returns a data sample to demonstrate
	// the structure of eCH-0108:organisationType. The sample contains
	// all mapped fields. All data is fictional.              </summary>
	//
	//	<returns>Data sample</returns>
	GetOrganisationSample(GetOrganisationSample *GetOrganisationSample) (*GetOrganisationSampleResponse, error)

	// <summary>             Search for UID-Einheiten
	//
	//	</summary>             <param name="searchParameters">Search
	//
	// parameters formated as eCH-0108-3-0f document</param>
	//
	//	<param name="config">Configuration parameters to customize
	//
	// search behaviour</param>             <returns>XML-Document
	// of type uid-wse</returns>
	Search(Search *Search) (*SearchResponse, error)

	// <summary>             Validate a UID              </summary>
	//
	//	<param name="uid">UID to validate. Accepted format:
	//
	// 'CHE123456789' or 'CHE-123.456.789'</param>             <returns>true
	// if the UID exists in the UID register</returns>
	ValidateUID(ValidateUID *ValidateUID) (*ValidateUIDResponse, error)

	// <summary>             Validate a VatNumber              </summary>
	//
	//	<param name="vatNumber">VAT number to validate</param>
	//	<returns>true if exists</returns>
	ValidateVatNumber(ValidateVatNumber *ValidateVatNumber) (*ValidateVatNumberResponse, error)
}

// Date in WSDL format.
type Date string

// AddressCategoryType was auto-generated from WSDL.
type AddressCategoryType string

// Validate validates AddressCategoryType.
func (v AddressCategoryType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// CantonAbbreviationType was auto-generated from WSDL.
type CantonAbbreviationType string

// Validate validates CantonAbbreviationType.
func (v CantonAbbreviationType) Validate() bool {
	for _, vv := range []string{
		"ZH",
		"BE",
		"LU",
		"UR",
		"SZ",
		"OW",
		"NW",
		"GL",
		"ZG",
		"FR",
		"SO",
		"BS",
		"BL",
		"SH",
		"AR",
		"AI",
		"SG",
		"GR",
		"AG",
		"TG",
		"TI",
		"VD",
		"VS",
		"NE",
		"GE",
		"JU",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// CommercialRegisterEnterpriseTypeType was auto-generated from
// WSDL.
type CommercialRegisterEnterpriseTypeType string

// Validate validates CommercialRegisterEnterpriseTypeType.
func (v CommercialRegisterEnterpriseTypeType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// CommercialRegisterEntryStatusType was auto-generated from WSDL.
type CommercialRegisterEntryStatusType string

// Validate validates CommercialRegisterEntryStatusType.
func (v CommercialRegisterEntryStatusType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
		"3",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// CommercialRegisterStatusType was auto-generated from WSDL.
type CommercialRegisterStatusType string

// Validate validates CommercialRegisterStatusType.
func (v CommercialRegisterStatusType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
		"3",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// EmailCategoryType was auto-generated from WSDL.
type EmailCategoryType string

// Validate validates EmailCategoryType.
func (v EmailCategoryType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// FoundationReasonType was auto-generated from WSDL.
type FoundationReasonType string

// Validate validates FoundationReasonType.
func (v FoundationReasonType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
		"3",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// InternetCategoryType was auto-generated from WSDL.
type InternetCategoryType string

// Validate validates InternetCategoryType.
func (v InternetCategoryType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// LiquidationReasonType was auto-generated from WSDL.
type LiquidationReasonType string

// Validate validates LiquidationReasonType.
func (v LiquidationReasonType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
		"3",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// MrMrsType was auto-generated from WSDL.
type MrMrsType string

// Validate validates MrMrsType.
func (v MrMrsType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
		"3",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// OrganisationMembershipRoleType was auto-generated from WSDL.
type OrganisationMembershipRoleType string

// Validate validates OrganisationMembershipRoleType.
func (v OrganisationMembershipRoleType) Validate() bool {
	for _, vv := range []string{
		"GroupHead",
		"GroupMember",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// PhoneCategoryType was auto-generated from WSDL.
type PhoneCategoryType string

// Validate validates PhoneCategoryType.
func (v PhoneCategoryType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// SearchMode was auto-generated from WSDL.
type SearchMode string

// Validate validates SearchMode.
func (v SearchMode) Validate() bool {
	for _, vv := range []string{
		"Auto",
		"Normal",
		"Fuzzy",
		"FuzzyPerson",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// SexType was auto-generated from WSDL.
type SexType string

// Validate validates SexType.
func (v SexType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
		"3",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// UidOrganisationIdCategorieType was auto-generated from WSDL.
type UidOrganisationIdCategorieType string

// Validate validates UidOrganisationIdCategorieType.
func (v UidOrganisationIdCategorieType) Validate() bool {
	for _, vv := range []string{
		"CHE",
		"ADM",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// UidregLiquidationReasonType was auto-generated from WSDL.
type UidregLiquidationReasonType string

// Validate validates UidregLiquidationReasonType.
func (v UidregLiquidationReasonType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// UidregOrganisationTypeType was auto-generated from WSDL.
type UidregOrganisationTypeType string

// Validate validates UidregOrganisationTypeType.
func (v UidregOrganisationTypeType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13",
		"14",
		"15",
		"16",
		"17",
		"18",
		"19",
		"99",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// UidregPublicStatusType was auto-generated from WSDL.
type UidregPublicStatusType string

// Validate validates UidregPublicStatusType.
func (v UidregPublicStatusType) Validate() bool {
	for _, vv := range []string{
		"0",
		"1",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// UidregStatusEnterpriseDetailType was auto-generated from WSDL.
type UidregStatusEnterpriseDetailType string

// Validate validates UidregStatusEnterpriseDetailType.
func (v UidregStatusEnterpriseDetailType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// VatEntryStatusType was auto-generated from WSDL.
type VatEntryStatusType string

// Validate validates VatEntryStatusType.
func (v VatEntryStatusType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// VatStatusType was auto-generated from WSDL.
type VatStatusType string

// Validate validates VatStatusType.
func (v VatStatusType) Validate() bool {
	for _, vv := range []string{
		"1",
		"2",
		"3",
	} {
		if reflect.DeepEqual(v, vv) {
			return true
		}
	}
	return false
}

// ArrayOfOrganisationType was auto-generated from WSDL.
type ArrayOfOrganisationType struct {
	OrganisationType []*OrganisationType `xml:"organisationType,omitempty" json:"organisationType,omitempty" yaml:"organisationType,omitempty"`
}

// GetByUID was auto-generated from WSDL.
type GetByUID struct {
	Uid *UidStructureType `xml:"uid,omitempty" json:"uid,omitempty" yaml:"uid,omitempty"`
}

// GetByUIDResponse was auto-generated from WSDL.
type GetByUIDResponse struct {
	GetByUIDResult *ArrayOfOrganisationType `xml:"GetByUIDResult,omitempty" json:"GetByUIDResult,omitempty" yaml:"GetByUIDResult,omitempty"`
}

// GetOrganisationSample was auto-generated from WSDL.
type GetOrganisationSample struct {
}

// GetOrganisationSampleResponse was auto-generated from WSDL.
type GetOrganisationSampleResponse struct {
	GetOrganisationSampleResult *OrganisationType `xml:"GetOrganisationSampleResult,omitempty" json:"GetOrganisationSampleResult,omitempty" yaml:"GetOrganisationSampleResult,omitempty"`
}

// Search was auto-generated from WSDL.
type Search struct {
	SearchParameters *UidEntityPublicSearchRequest `xml:"searchParameters,omitempty" json:"searchParameters,omitempty" yaml:"searchParameters,omitempty"`
	Config           *SearchConfiguration          `xml:"config,omitempty" json:"config,omitempty" yaml:"config,omitempty"`
}

// SearchResponse was auto-generated from WSDL.
type SearchResponse struct {
	SearchResult *UidEntitySearchResponse `xml:"SearchResult,omitempty" json:"SearchResult,omitempty" yaml:"SearchResult,omitempty"`
}

// ValidateUID was auto-generated from WSDL.
type ValidateUID struct {
	Uid *string `xml:"uid,omitempty" json:"uid,omitempty" yaml:"uid,omitempty"`
}

// ValidateUIDResponse was auto-generated from WSDL.
type ValidateUIDResponse struct {
	ValidateUIDResult bool `xml:"ValidateUIDResult" json:"ValidateUIDResult" yaml:"ValidateUIDResult"`
}

// ValidateVatNumber was auto-generated from WSDL.
type ValidateVatNumber struct {
	VatNumber *string `xml:"vatNumber,omitempty" json:"vatNumber,omitempty" yaml:"vatNumber,omitempty"`
}

// ValidateVatNumberResponse was auto-generated from WSDL.
type ValidateVatNumberResponse struct {
	ValidateVatNumberResult bool `xml:"ValidateVatNumberResult" json:"ValidateVatNumberResult" yaml:"ValidateVatNumberResult"`
}

// AddressInformationType was auto-generated from WSDL.
type AddressInformationType struct {
	AddressLine1        *string      `xml:"http://www.ech.ch/xmlns/eCH-0010/7 addressLine1,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 addressLine1,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 addressLine1,omitempty"`
	AddressLine2        *string      `xml:"http://www.ech.ch/xmlns/eCH-0010/7 addressLine2,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 addressLine2,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 addressLine2,omitempty"`
	Street              *string      `xml:"http://www.ech.ch/xmlns/eCH-0010/7 street,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 street,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 street,omitempty"`
	HouseNumber         *string      `xml:"http://www.ech.ch/xmlns/eCH-0010/7 houseNumber,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 houseNumber,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 houseNumber,omitempty"`
	DwellingNumber      *string      `xml:"http://www.ech.ch/xmlns/eCH-0010/7 dwellingNumber,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 dwellingNumber,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 dwellingNumber,omitempty"`
	PostOfficeBoxNumber *uint        `xml:"http://www.ech.ch/xmlns/eCH-0010/7 postOfficeBoxNumber,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 postOfficeBoxNumber,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 postOfficeBoxNumber,omitempty"`
	PostOfficeBoxText   *string      `xml:"http://www.ech.ch/xmlns/eCH-0010/7 postOfficeBoxText,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 postOfficeBoxText,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 postOfficeBoxText,omitempty"`
	Locality            *string      `xml:"http://www.ech.ch/xmlns/eCH-0010/7 locality,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 locality,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 locality,omitempty"`
	Town                *string      `xml:"http://www.ech.ch/xmlns/eCH-0010/7 town,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 town,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 town,omitempty"`
	Country             *CountryType `xml:"http://www.ech.ch/xmlns/eCH-0010/7 country,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 country,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 country,omitempty"`
	ForeignZipCode      *string      `xml:"http://www.ech.ch/xmlns/eCH-0010/7 foreignZipCode,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 foreignZipCode,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 foreignZipCode,omitempty"`
	SwissZipCode        uint         `xml:"http://www.ech.ch/xmlns/eCH-0010/7 swissZipCode" json:"http://www.ech.ch/xmlns/eCH-0010/7 swissZipCode" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 swissZipCode"`
	SwissZipCodeAddOn   *string      `xml:"http://www.ech.ch/xmlns/eCH-0010/7 swissZipCodeAddOn,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 swissZipCodeAddOn,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 swissZipCodeAddOn,omitempty"`
	SwissZipCodeId      int          `xml:"http://www.ech.ch/xmlns/eCH-0010/7 swissZipCodeId" json:"http://www.ech.ch/xmlns/eCH-0010/7 swissZipCodeId" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 swissZipCodeId"`
}

// AddressSearchType was auto-generated from WSDL.
type AddressSearchType struct {
	AddressLine1        *string                `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 addressLine1,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 addressLine1,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 addressLine1,omitempty"`
	AddressLine2        *string                `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 addressLine2,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 addressLine2,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 addressLine2,omitempty"`
	Street              *string                `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 street,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 street,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 street,omitempty"`
	HouseNumber         *string                `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 houseNumber,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 houseNumber,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 houseNumber,omitempty"`
	PostOfficeBoxNumber *uint                  `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 postOfficeBoxNumber,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 postOfficeBoxNumber,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 postOfficeBoxNumber,omitempty"`
	Town                *string                `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 town,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 town,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 town,omitempty"`
	CountryIdISO2       *string                `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 countryIdISO2,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 countryIdISO2,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 countryIdISO2,omitempty"`
	SwissZipCode        uint                   `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 swissZipCode" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 swissZipCode" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 swissZipCode"`
	SwissZipCodeAddOn   *string                `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 swissZipCodeAddOn,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 swissZipCodeAddOn,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 swissZipCodeAddOn,omitempty"`
	MunicipalityId      int                    `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 municipalityId" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 municipalityId" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 municipalityId"`
	CantonAbbreviation  CantonAbbreviationType `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 cantonAbbreviation" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 cantonAbbreviation" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 cantonAbbreviation"`
	EGID                uint                   `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 EGID" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 EGID" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 EGID"`
	ForeignZipCode      *string                `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 foreignZipCode,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 foreignZipCode,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 foreignZipCode,omitempty"`
}

// AddressType was auto-generated from WSDL.
type AddressType struct {
	PostalAddress        *MailAddressType    `xml:"http://www.ech.ch/xmlns/eCH-0046/5 postalAddress,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 postalAddress,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 postalAddress,omitempty"`
	Validity             *DateRangeType      `xml:"http://www.ech.ch/xmlns/eCH-0046/5 validity,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 validity,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 validity,omitempty"`
	AddressCategory      AddressCategoryType `xml:"http://www.ech.ch/xmlns/eCH-0046/5 addressCategory" json:"http://www.ech.ch/xmlns/eCH-0046/5 addressCategory" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 addressCategory"`
	OtherAddressCategory *string             `xml:"http://www.ech.ch/xmlns/eCH-0046/5 otherAddressCategory,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 otherAddressCategory,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 otherAddressCategory,omitempty"`
}

// BusinessFault was auto-generated from WSDL.
type BusinessFault struct {
	Operation     *string `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty"`
	Error         *string `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty"`
	ErrorDetail   *string `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty"`
	TypeAttrXSI   string  `xml:"xsi:type,attr,omitempty"`
	TypeNamespace string  `xml:"xmlns:objtype,attr,omitempty"`

	OverrideTypeAttrXSI   *string `xml:"-"`
	OverrideTypeNamespace *string `xml:"-"`
}

// SetXMLType was auto-generated from WSDL.
func (t *BusinessFault) SetXMLType() {
	if t.OverrideTypeAttrXSI != nil {
		t.TypeAttrXSI = *t.OverrideTypeAttrXSI
	} else {
		t.TypeAttrXSI = "objtype:businessFault"
	}
	if t.OverrideTypeNamespace != nil {
		t.TypeNamespace = *t.OverrideTypeNamespace
	} else {
		t.TypeNamespace = "http://www.uid.admin.ch/xmlns/uid-wse-shared/2"
	}
}

// CommercialRegisterInformationSearchType was auto-generated from
// WSDL.
type CommercialRegisterInformationSearchType struct {
	CommercialRegisterStatus          *CommercialRegisterStatusType         `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterStatus,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterStatus,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterStatus,omitempty"`
	CommercialRegisterEntryStatus     *CommercialRegisterEntryStatusType    `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterEntryStatus,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterEntryStatus,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterEntryStatus,omitempty"`
	CommercialRegisterEntryDate       *Date                                 `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterEntryDate,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterEntryDate,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterEntryDate,omitempty"`
	CommercialRegisterLiquidationDate *Date                                 `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterLiquidationDate,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterLiquidationDate,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterLiquidationDate,omitempty"`
	CommercialRegisterEnterpriseType  *CommercialRegisterEnterpriseTypeType `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterEnterpriseType,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterEnterpriseType,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterEnterpriseType,omitempty"`
}

// CommercialRegisterInformationType was auto-generated from WSDL.
type CommercialRegisterInformationType struct {
	CommercialRegisterStatus          CommercialRegisterStatusType          `xml:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterStatus" json:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterStatus" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterStatus"`
	CommercialRegisterEntryStatus     *CommercialRegisterEntryStatusType    `xml:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterEntryStatus,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterEntryStatus,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterEntryStatus,omitempty"`
	CommercialRegisterNameTranslation *string                               `xml:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterNameTranslation,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterNameTranslation,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterNameTranslation,omitempty"`
	CommercialRegisterEntryDate       *Date                                 `xml:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterEntryDate,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterEntryDate,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterEntryDate,omitempty"`
	CommercialRegisterLiquidationDate *Date                                 `xml:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterLiquidationDate,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterLiquidationDate,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterLiquidationDate,omitempty"`
	CommercialRegisterEnterpriseType  *CommercialRegisterEnterpriseTypeType `xml:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterEnterpriseType,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterEnterpriseType,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 commercialRegisterEnterpriseType,omitempty"`
}

// ContactType was auto-generated from WSDL.
type ContactType struct {
	LocalID  *NamedPersonIdType `xml:"http://www.ech.ch/xmlns/eCH-0046/5 localID,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 localID,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 localID,omitempty"`
	Address  []*AddressType     `xml:"http://www.ech.ch/xmlns/eCH-0046/5 address,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 address,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 address,omitempty"`
	Email    []*EmailType       `xml:"http://www.ech.ch/xmlns/eCH-0046/5 email,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 email,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 email,omitempty"`
	Phone    []*PhoneType       `xml:"http://www.ech.ch/xmlns/eCH-0046/5 phone,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 phone,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 phone,omitempty"`
	Internet []*InternetType    `xml:"http://www.ech.ch/xmlns/eCH-0046/5 internet,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 internet,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 internet,omitempty"`
}

// CountryType was auto-generated from WSDL.
type CountryType struct {
	CountryId        *int64  `xml:"http://www.ech.ch/xmlns/eCH-0010/7 countryId,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 countryId,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 countryId,omitempty"`
	CountryIdISO2    *string `xml:"http://www.ech.ch/xmlns/eCH-0010/7 countryIdISO2,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 countryIdISO2,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 countryIdISO2,omitempty"`
	CountryNameShort *string `xml:"http://www.ech.ch/xmlns/eCH-0010/7 countryNameShort,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 countryNameShort,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 countryNameShort,omitempty"`
}

// DatePartiallyKnownType was auto-generated from WSDL.
type DatePartiallyKnownType struct {
	Year         *GYear      `xml:"http://www.ech.ch/xmlns/eCH-0098/5 year,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 year,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 year,omitempty"`
	YearMonth    *GYearMonth `xml:"http://www.ech.ch/xmlns/eCH-0098/5 yearMonth,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 yearMonth,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 yearMonth,omitempty"`
	YearMonthDay Date        `xml:"http://www.ech.ch/xmlns/eCH-0098/5 yearMonthDay" json:"http://www.ech.ch/xmlns/eCH-0098/5 yearMonthDay" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 yearMonthDay"`
}

// DateRangeType was auto-generated from WSDL.
type DateRangeType struct {
	DateFrom *Date `xml:"http://www.ech.ch/xmlns/eCH-0046/5 dateFrom,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 dateFrom,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 dateFrom,omitempty"`
	DateTo   *Date `xml:"http://www.ech.ch/xmlns/eCH-0046/5 dateTo,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 dateTo,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 dateTo,omitempty"`
}

// DuplicateCandidateType was auto-generated from WSDL.
type DuplicateCandidateType struct {
	Rating                       int                              `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 rating" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 rating" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 rating"`
	Uid                          *UidStructureType                `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uid,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 uid,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uid,omitempty"`
	OrganisationName             *string                          `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 organisationName,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 organisationName,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 organisationName,omitempty"`
	OrganisationAdditionalName   *string                          `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 organisationAdditionalName,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 organisationAdditionalName,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 organisationAdditionalName,omitempty"`
	Street                       *string                          `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 street,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 street,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 street,omitempty"`
	SwissZipCode                 uint                             `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 swissZipCode" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 swissZipCode" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 swissZipCode"`
	Town                         *string                          `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 town,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 town,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 town,omitempty"`
	UidregStatusEnterpriseDetail UidregStatusEnterpriseDetailType `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregStatusEnterpriseDetail" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregStatusEnterpriseDetail" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregStatusEnterpriseDetail"`
	UidregOrganisationType       UidregOrganisationTypeType       `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregOrganisationType" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregOrganisationType" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregOrganisationType"`
}

// DuplicateFault was auto-generated from WSDL.
type DuplicateFault struct {
	Operation             *string                   `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty"`
	Error                 *string                   `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty"`
	ErrorDetail           *string                   `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty"`
	Candidates            []*DuplicateCandidateType `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 candidates,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 candidates,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 candidates,omitempty"`
	DuplicateOverrideCode *string                   `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 duplicateOverrideCode,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 duplicateOverrideCode,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 duplicateOverrideCode,omitempty"`
	TypeAttrXSI           string                    `xml:"xsi:type,attr,omitempty"`
	TypeNamespace         string                    `xml:"xmlns:objtype,attr,omitempty"`

	OverrideTypeAttrXSI   *string `xml:"-"`
	OverrideTypeNamespace *string `xml:"-"`
}

// SetXMLType was auto-generated from WSDL.
func (t *DuplicateFault) SetXMLType() {
	if t.OverrideTypeAttrXSI != nil {
		t.TypeAttrXSI = *t.OverrideTypeAttrXSI
	} else {
		t.TypeAttrXSI = "objtype:duplicateFault"
	}
	if t.OverrideTypeNamespace != nil {
		t.TypeNamespace = *t.OverrideTypeNamespace
	} else {
		t.TypeNamespace = "http://www.uid.admin.ch/xmlns/uid-wse/5"
	}
}

// EmailType was auto-generated from WSDL.
type EmailType struct {
	EmailAddress       *string           `xml:"http://www.ech.ch/xmlns/eCH-0046/5 emailAddress,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 emailAddress,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 emailAddress,omitempty"`
	Validity           *DateRangeType    `xml:"http://www.ech.ch/xmlns/eCH-0046/5 validity,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 validity,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 validity,omitempty"`
	EmailCategory      EmailCategoryType `xml:"http://www.ech.ch/xmlns/eCH-0046/5 emailCategory" json:"http://www.ech.ch/xmlns/eCH-0046/5 emailCategory" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 emailCategory"`
	OtherEmailCategory *string           `xml:"http://www.ech.ch/xmlns/eCH-0046/5 otherEmailCategory,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 otherEmailCategory,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 otherEmailCategory,omitempty"`
}

// FoundationType was auto-generated from WSDL.
type FoundationType struct {
	FoundationDate   *DatePartiallyKnownType `xml:"http://www.ech.ch/xmlns/eCH-0098/5 foundationDate,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 foundationDate,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 foundationDate,omitempty"`
	FoundationReason *FoundationReasonType   `xml:"http://www.ech.ch/xmlns/eCH-0098/5 foundationReason,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 foundationReason,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 foundationReason,omitempty"`
}

// GroupRelationshipType was auto-generated from WSDL.
type GroupRelationshipType struct {
	GroupName                  *string                        `xml:"http://www.ech.ch/xmlns/eCH-0108/5 groupName,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 groupName,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 groupName,omitempty"`
	OrganisationMembershipRole OrganisationMembershipRoleType `xml:"http://www.ech.ch/xmlns/eCH-0108/5 organisationMembershipRole" json:"http://www.ech.ch/xmlns/eCH-0108/5 organisationMembershipRole" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 organisationMembershipRole"`
	GroupParticipant           []*string                      `xml:"http://www.ech.ch/xmlns/eCH-0108/5 groupParticipant,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 groupParticipant,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 groupParticipant,omitempty"`
}

// InfrastructureFault was auto-generated from WSDL.
type InfrastructureFault struct {
	Operation     *string `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty"`
	Error         *string `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty"`
	ErrorDetail   *string `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty"`
	TypeAttrXSI   string  `xml:"xsi:type,attr,omitempty"`
	TypeNamespace string  `xml:"xmlns:objtype,attr,omitempty"`

	OverrideTypeAttrXSI   *string `xml:"-"`
	OverrideTypeNamespace *string `xml:"-"`
}

// SetXMLType was auto-generated from WSDL.
func (t *InfrastructureFault) SetXMLType() {
	if t.OverrideTypeAttrXSI != nil {
		t.TypeAttrXSI = *t.OverrideTypeAttrXSI
	} else {
		t.TypeAttrXSI = "objtype:infrastructureFault"
	}
	if t.OverrideTypeNamespace != nil {
		t.TypeNamespace = *t.OverrideTypeNamespace
	} else {
		t.TypeNamespace = "http://www.uid.admin.ch/xmlns/uid-wse-shared/2"
	}
}

// InternetType was auto-generated from WSDL.
type InternetType struct {
	InternetAddress       *string              `xml:"http://www.ech.ch/xmlns/eCH-0046/5 internetAddress,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 internetAddress,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 internetAddress,omitempty"`
	Validity              *DateRangeType       `xml:"http://www.ech.ch/xmlns/eCH-0046/5 validity,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 validity,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 validity,omitempty"`
	InternetCategory      InternetCategoryType `xml:"http://www.ech.ch/xmlns/eCH-0046/5 internetCategory" json:"http://www.ech.ch/xmlns/eCH-0046/5 internetCategory" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 internetCategory"`
	OtherInternetCategory *string              `xml:"http://www.ech.ch/xmlns/eCH-0046/5 otherInternetCategory,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 otherInternetCategory,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 otherInternetCategory,omitempty"`
}

// InvolvedPersonType was auto-generated from WSDL.
type InvolvedPersonType struct {
	Role         *string                 `xml:"http://www.ech.ch/xmlns/eCH-0108/5 role,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 role,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 role,omitempty"`
	Vn           *UnsignedLong           `xml:"http://www.ech.ch/xmlns/eCH-0108/5 vn,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 vn,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 vn,omitempty"`
	OfficialName *string                 `xml:"http://www.ech.ch/xmlns/eCH-0108/5 officialName,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 officialName,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 officialName,omitempty"`
	FirstName    *string                 `xml:"http://www.ech.ch/xmlns/eCH-0108/5 firstName,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 firstName,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 firstName,omitempty"`
	DateOfBirth  *DatePartiallyKnownType `xml:"http://www.ech.ch/xmlns/eCH-0108/5 dateOfBirth,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 dateOfBirth,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 dateOfBirth,omitempty"`
	Sex          *SexType                `xml:"http://www.ech.ch/xmlns/eCH-0108/5 sex,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 sex,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 sex,omitempty"`
}

// LeiRegisterInformationType was auto-generated from WSDL.
type LeiRegisterInformationType struct {
	InitialRegistrationDate Date   `xml:"http://www.ech.ch/xmlns/eCH-0108/5 initialRegistrationDate" json:"http://www.ech.ch/xmlns/eCH-0108/5 initialRegistrationDate" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 initialRegistrationDate"`
	ExpirationDate          *Date  `xml:"http://www.ech.ch/xmlns/eCH-0108/5 expirationDate,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 expirationDate,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 expirationDate,omitempty"`
	RegistrationStatus      string `xml:"http://www.ech.ch/xmlns/eCH-0108/5 registrationStatus" json:"http://www.ech.ch/xmlns/eCH-0108/5 registrationStatus" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 registrationStatus"`
}

// LiquidationType was auto-generated from WSDL.
type LiquidationType struct {
	LiquidationDate      *DatePartiallyKnownType `xml:"http://www.ech.ch/xmlns/eCH-0098/5 liquidationDate,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 liquidationDate,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 liquidationDate,omitempty"`
	LiquidationStartDate *DatePartiallyKnownType `xml:"http://www.ech.ch/xmlns/eCH-0098/5 liquidationStartDate,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 liquidationStartDate,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 liquidationStartDate,omitempty"`
	LiquidationReason    *LiquidationReasonType  `xml:"http://www.ech.ch/xmlns/eCH-0098/5 liquidationReason,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 liquidationReason,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 liquidationReason,omitempty"`
}

// MailAddressType was auto-generated from WSDL.
type MailAddressType struct {
	AddressInformation *AddressInformationType          `xml:"http://www.ech.ch/xmlns/eCH-0010/7 addressInformation,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 addressInformation,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 addressInformation,omitempty"`
	Organisation       *OrganisationMailAddressInfoType `xml:"http://www.ech.ch/xmlns/eCH-0010/7 organisation,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 organisation,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 organisation,omitempty"`
	Person             *PersonMailAddressInfoType       `xml:"http://www.ech.ch/xmlns/eCH-0010/7 person,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 person,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 person,omitempty"`
}

// NamedOrganisationIdType was auto-generated from WSDL.
type NamedOrganisationIdType struct {
	OrganisationIdCategory *string `xml:"http://www.ech.ch/xmlns/eCH-0097/5 organisationIdCategory,omitempty" json:"http://www.ech.ch/xmlns/eCH-0097/5 organisationIdCategory,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0097/5 organisationIdCategory,omitempty"`
	OrganisationId         *string `xml:"http://www.ech.ch/xmlns/eCH-0097/5 organisationId,omitempty" json:"http://www.ech.ch/xmlns/eCH-0097/5 organisationId,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0097/5 organisationId,omitempty"`
}

// NamedPersonIdType was auto-generated from WSDL.
type NamedPersonIdType struct {
	PersonIdCategory *string `xml:"http://www.ech.ch/xmlns/eCH-0044/4 personIdCategory,omitempty" json:"http://www.ech.ch/xmlns/eCH-0044/4 personIdCategory,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0044/4 personIdCategory,omitempty"`
	PersonId         *string `xml:"http://www.ech.ch/xmlns/eCH-0044/4 personId,omitempty" json:"http://www.ech.ch/xmlns/eCH-0044/4 personId,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0044/4 personId,omitempty"`
}

// OrganisationAddressType was auto-generated from WSDL.
type OrganisationAddressType struct {
	AddressCategory     *string                `xml:"http://www.ech.ch/xmlns/eCH-0098/5 addressCategory,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 addressCategory,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 addressCategory,omitempty"`
	AddressLine1        *string                `xml:"http://www.ech.ch/xmlns/eCH-0098/5 addressLine1,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 addressLine1,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 addressLine1,omitempty"`
	AddressLine2        *string                `xml:"http://www.ech.ch/xmlns/eCH-0098/5 addressLine2,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 addressLine2,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 addressLine2,omitempty"`
	Street              *string                `xml:"http://www.ech.ch/xmlns/eCH-0098/5 street,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 street,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 street,omitempty"`
	HouseNumber         *string                `xml:"http://www.ech.ch/xmlns/eCH-0098/5 houseNumber,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 houseNumber,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 houseNumber,omitempty"`
	DwellingNumber      *string                `xml:"http://www.ech.ch/xmlns/eCH-0098/5 dwellingNumber,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 dwellingNumber,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 dwellingNumber,omitempty"`
	PostOfficeBoxNumber *uint                  `xml:"http://www.ech.ch/xmlns/eCH-0098/5 postOfficeBoxNumber,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 postOfficeBoxNumber,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 postOfficeBoxNumber,omitempty"`
	Town                *string                `xml:"http://www.ech.ch/xmlns/eCH-0098/5 town,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 town,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 town,omitempty"`
	CountryIdISO2       *string                `xml:"http://www.ech.ch/xmlns/eCH-0098/5 countryIdISO2,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 countryIdISO2,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 countryIdISO2,omitempty"`
	DeliverableYesNo    *bool                  `xml:"http://www.ech.ch/xmlns/eCH-0098/5 deliverableYesNo,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 deliverableYesNo,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 deliverableYesNo,omitempty"`
	DateOfLastCheck     *Date                  `xml:"http://www.ech.ch/xmlns/eCH-0098/5 dateOfLastCheck,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 dateOfLastCheck,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 dateOfLastCheck,omitempty"`
	SwissZipCode        uint                   `xml:"http://www.ech.ch/xmlns/eCH-0098/5 swissZipCode" json:"http://www.ech.ch/xmlns/eCH-0098/5 swissZipCode" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 swissZipCode"`
	SwissZipCodeAddOn   *string                `xml:"http://www.ech.ch/xmlns/eCH-0098/5 swissZipCodeAddOn,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 swissZipCodeAddOn,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 swissZipCodeAddOn,omitempty"`
	MunicipalityId      int                    `xml:"http://www.ech.ch/xmlns/eCH-0098/5 municipalityId" json:"http://www.ech.ch/xmlns/eCH-0098/5 municipalityId" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 municipalityId"`
	CantonAbbreviation  CantonAbbreviationType `xml:"http://www.ech.ch/xmlns/eCH-0098/5 cantonAbbreviation" json:"http://www.ech.ch/xmlns/eCH-0098/5 cantonAbbreviation" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 cantonAbbreviation"`
	EGID                uint                   `xml:"http://www.ech.ch/xmlns/eCH-0098/5 EGID" json:"http://www.ech.ch/xmlns/eCH-0098/5 EGID" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 EGID"`
	ForeignZipCode      *string                `xml:"http://www.ech.ch/xmlns/eCH-0098/5 foreignZipCode,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 foreignZipCode,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 foreignZipCode,omitempty"`
}

// OrganisationIdentificationType was auto-generated from WSDL.
type OrganisationIdentificationType struct {
	Uid                        *UidStructureType          `xml:"http://www.ech.ch/xmlns/eCH-0097/5 uid,omitempty" json:"http://www.ech.ch/xmlns/eCH-0097/5 uid,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0097/5 uid,omitempty"`
	LocalOrganisationId        *NamedOrganisationIdType   `xml:"http://www.ech.ch/xmlns/eCH-0097/5 localOrganisationId,omitempty" json:"http://www.ech.ch/xmlns/eCH-0097/5 localOrganisationId,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0097/5 localOrganisationId,omitempty"`
	OtherOrganisationId        []*NamedOrganisationIdType `xml:"http://www.ech.ch/xmlns/eCH-0097/5 OtherOrganisationId,omitempty" json:"http://www.ech.ch/xmlns/eCH-0097/5 OtherOrganisationId,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0097/5 OtherOrganisationId,omitempty"`
	OrganisationName           *string                    `xml:"http://www.ech.ch/xmlns/eCH-0097/5 organisationName,omitempty" json:"http://www.ech.ch/xmlns/eCH-0097/5 organisationName,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0097/5 organisationName,omitempty"`
	OrganisationLegalName      *string                    `xml:"http://www.ech.ch/xmlns/eCH-0097/5 organisationLegalName,omitempty" json:"http://www.ech.ch/xmlns/eCH-0097/5 organisationLegalName,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0097/5 organisationLegalName,omitempty"`
	OrganisationAdditionalName *string                    `xml:"http://www.ech.ch/xmlns/eCH-0097/5 organisationAdditionalName,omitempty" json:"http://www.ech.ch/xmlns/eCH-0097/5 organisationAdditionalName,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0097/5 organisationAdditionalName,omitempty"`
	LegalForm                  *string                    `xml:"http://www.ech.ch/xmlns/eCH-0097/5 legalForm,omitempty" json:"http://www.ech.ch/xmlns/eCH-0097/5 legalForm,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0097/5 legalForm,omitempty"`
}

// OrganisationMailAddressInfoType was auto-generated from WSDL.
type OrganisationMailAddressInfoType struct {
	OrganisationName       *string    `xml:"http://www.ech.ch/xmlns/eCH-0010/7 organisationName,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 organisationName,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 organisationName,omitempty"`
	OrganisationNameAddOn1 *string    `xml:"http://www.ech.ch/xmlns/eCH-0010/7 organisationNameAddOn1,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 organisationNameAddOn1,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 organisationNameAddOn1,omitempty"`
	OrganisationNameAddOn2 *string    `xml:"http://www.ech.ch/xmlns/eCH-0010/7 organisationNameAddOn2,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 organisationNameAddOn2,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 organisationNameAddOn2,omitempty"`
	MrMrs                  *MrMrsType `xml:"http://www.ech.ch/xmlns/eCH-0010/7 mrMrs,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 mrMrs,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 mrMrs,omitempty"`
	Title                  *string    `xml:"http://www.ech.ch/xmlns/eCH-0010/7 title,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 title,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 title,omitempty"`
	FirstName              *string    `xml:"http://www.ech.ch/xmlns/eCH-0010/7 firstName,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 firstName,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 firstName,omitempty"`
	LastName               *string    `xml:"http://www.ech.ch/xmlns/eCH-0010/7 lastName,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 lastName,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 lastName,omitempty"`
}

// OrganisationType was auto-generated from WSDL.
type OrganisationType struct {
	OrganisationIdentification *OrganisationIdentificationType `xml:"http://www.ech.ch/xmlns/eCH-0098/5 organisationIdentification,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 organisationIdentification,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 organisationIdentification,omitempty"`
	UidBrancheText             *string                         `xml:"http://www.ech.ch/xmlns/eCH-0098/5 uidBrancheText,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 uidBrancheText,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 uidBrancheText,omitempty"`
	NOGACode                   *string                         `xml:"http://www.ech.ch/xmlns/eCH-0098/5 NOGACode,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 NOGACode,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 NOGACode,omitempty"`
	Foundation                 *FoundationType                 `xml:"http://www.ech.ch/xmlns/eCH-0098/5 foundation,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 foundation,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 foundation,omitempty"`
	Liquidation                *LiquidationType                `xml:"http://www.ech.ch/xmlns/eCH-0098/5 liquidation,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 liquidation,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 liquidation,omitempty"`
	Address                    []*OrganisationAddressType      `xml:"http://www.ech.ch/xmlns/eCH-0098/5 address,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 address,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 address,omitempty"`
	Contact                    *ContactType                    `xml:"http://www.ech.ch/xmlns/eCH-0098/5 contact,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 contact,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 contact,omitempty"`
	LanguageOfCorrespondance   *string                         `xml:"http://www.ech.ch/xmlns/eCH-0098/5 languageOfCorrespondance,omitempty" json:"http://www.ech.ch/xmlns/eCH-0098/5 languageOfCorrespondance,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0098/5 languageOfCorrespondance,omitempty"`
}

// PersonMailAddressInfoType was auto-generated from WSDL.
type PersonMailAddressInfoType struct {
	MrMrs     *MrMrsType `xml:"http://www.ech.ch/xmlns/eCH-0010/7 mrMrs,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 mrMrs,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 mrMrs,omitempty"`
	Title     *string    `xml:"http://www.ech.ch/xmlns/eCH-0010/7 title,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 title,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 title,omitempty"`
	FirstName *string    `xml:"http://www.ech.ch/xmlns/eCH-0010/7 firstName,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 firstName,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 firstName,omitempty"`
	LastName  *string    `xml:"http://www.ech.ch/xmlns/eCH-0010/7 lastName,omitempty" json:"http://www.ech.ch/xmlns/eCH-0010/7 lastName,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0010/7 lastName,omitempty"`
}

// PersonNameType was auto-generated from WSDL.
type PersonNameType struct {
	OfficialName *string `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 officialName,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 officialName,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 officialName,omitempty"`
	FirstName    *string `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 firstName,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 firstName,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 firstName,omitempty"`
}

// PhoneType was auto-generated from WSDL.
type PhoneType struct {
	PhoneNumber        *string           `xml:"http://www.ech.ch/xmlns/eCH-0046/5 phoneNumber,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 phoneNumber,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 phoneNumber,omitempty"`
	Validity           *DateRangeType    `xml:"http://www.ech.ch/xmlns/eCH-0046/5 validity,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 validity,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 validity,omitempty"`
	OtherPhoneCategory *string           `xml:"http://www.ech.ch/xmlns/eCH-0046/5 otherPhoneCategory,omitempty" json:"http://www.ech.ch/xmlns/eCH-0046/5 otherPhoneCategory,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 otherPhoneCategory,omitempty"`
	PhoneCategory      PhoneCategoryType `xml:"http://www.ech.ch/xmlns/eCH-0046/5 phoneCategory" json:"http://www.ech.ch/xmlns/eCH-0046/5 phoneCategory" yaml:"http://www.ech.ch/xmlns/eCH-0046/5 phoneCategory"`
}

// ReportingRegister was auto-generated from WSDL.
type ReportingRegister struct {
	UidOrganisationIdCategorie UidOrganisationIdCategorieType `xml:"http://www.ech.ch/xmlns/eCH-0097/5 uidOrganisationIdCategorie" json:"http://www.ech.ch/xmlns/eCH-0097/5 uidOrganisationIdCategorie" yaml:"http://www.ech.ch/xmlns/eCH-0097/5 uidOrganisationIdCategorie"`
	UidOrganisationId          *uint                          `xml:"http://www.ech.ch/xmlns/eCH-0097/5 uidOrganisationId,omitempty" json:"http://www.ech.ch/xmlns/eCH-0097/5 uidOrganisationId,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0097/5 uidOrganisationId,omitempty"`
	TypeAttrXSI                string                         `xml:"xsi:type,attr,omitempty"`
	TypeNamespace              string                         `xml:"xmlns:objtype,attr,omitempty"`

	OverrideTypeAttrXSI   *string `xml:"-"`
	OverrideTypeNamespace *string `xml:"-"`
}

// SetXMLType was auto-generated from WSDL.
func (t *ReportingRegister) SetXMLType() {
	if t.OverrideTypeAttrXSI != nil {
		t.TypeAttrXSI = *t.OverrideTypeAttrXSI
	} else {
		t.TypeAttrXSI = "objtype:reportingRegister"
	}
	if t.OverrideTypeNamespace != nil {
		t.TypeNamespace = *t.OverrideTypeNamespace
	} else {
		t.TypeNamespace = "http://www.ech.ch/xmlns/eCH-0116/4"
	}
}

// SearchConfiguration was auto-generated from WSDL.
type SearchConfiguration struct {
	SearchMode                  SearchMode `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 searchMode" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 searchMode" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 searchMode"`
	MaxNumberOfRecords          int        `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 maxNumberOfRecords" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 maxNumberOfRecords" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 maxNumberOfRecords"`
	SearchNameAndAddressHistory bool       `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 searchNameAndAddressHistory" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 searchNameAndAddressHistory" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 searchNameAndAddressHistory"`
}

// SecurityFault was auto-generated from WSDL.
type SecurityFault struct {
	Operation     *string `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty"`
	Error         *string `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty"`
	ErrorDetail   *string `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty"`
	TypeAttrXSI   string  `xml:"xsi:type,attr,omitempty"`
	TypeNamespace string  `xml:"xmlns:objtype,attr,omitempty"`

	OverrideTypeAttrXSI   *string `xml:"-"`
	OverrideTypeNamespace *string `xml:"-"`
}

// SetXMLType was auto-generated from WSDL.
func (t *SecurityFault) SetXMLType() {
	if t.OverrideTypeAttrXSI != nil {
		t.TypeAttrXSI = *t.OverrideTypeAttrXSI
	} else {
		t.TypeAttrXSI = "objtype:securityFault"
	}
	if t.OverrideTypeNamespace != nil {
		t.TypeNamespace = *t.OverrideTypeNamespace
	} else {
		t.TypeNamespace = "http://www.uid.admin.ch/xmlns/uid-wse-shared/2"
	}
}

// ServiceFault was auto-generated from WSDL.
type ServiceFault struct {
	Operation   *string `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 operation,omitempty"`
	Error       *string `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 error,omitempty"`
	ErrorDetail *string `xml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse-shared/2 errorDetail,omitempty"`
}

// UidEntityPublicSearchParameters was auto-generated from WSDL.
type UidEntityPublicSearchParameters struct {
	OrganisationName              *string                                  `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 organisationName,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 organisationName,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 organisationName,omitempty"`
	PersonName                    *PersonNameType                          `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 personName,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 personName,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 personName,omitempty"`
	Address                       *AddressSearchType                       `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 address,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 address,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 address,omitempty"`
	LegalForm                     []*string                                `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 legalForm,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 legalForm,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 legalForm,omitempty"`
	UidregInformation             *UidregInformationPublicSearchType       `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregInformation,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregInformation,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregInformation,omitempty"`
	CommercialRegisterInformation *CommercialRegisterInformationSearchType `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterInformation,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterInformation,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 commercialRegisterInformation,omitempty"`
	VatRegisterInformation        *VatRegisterInformationSearchType        `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatRegisterInformation,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatRegisterInformation,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatRegisterInformation,omitempty"`
}

// UidEntityPublicSearchRequest was auto-generated from WSDL.
type UidEntityPublicSearchRequest struct {
	Uid                       *UidStructureType                `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uid,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 uid,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uid,omitempty"`
	OtherOrganisationId       *NamedOrganisationIdType         `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 otherOrganisationId,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 otherOrganisationId,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 otherOrganisationId,omitempty"`
	UidEntitySearchParameters *UidEntityPublicSearchParameters `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidEntitySearchParameters,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidEntitySearchParameters,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidEntitySearchParameters,omitempty"`
}

// UidEntitySearchResponse was auto-generated from WSDL.
type UidEntitySearchResponse struct {
	UidEntitySearchResultItem []*UidEntitySearchResultItem `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidEntitySearchResultItem,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidEntitySearchResultItem,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidEntitySearchResultItem,omitempty"`
	Extension                 *string                      `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 extension,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 extension,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 extension,omitempty"`
}

// UidEntitySearchResultItem was auto-generated from WSDL.
type UidEntitySearchResultItem struct {
	Organisation   *OrganisationType `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 organisation,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 organisation,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 organisation,omitempty"`
	Rating         int               `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 rating" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 rating" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 rating"`
	IsHistoryMatch bool              `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 isHistoryMatch" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 isHistoryMatch" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 isHistoryMatch"`
	Extension      *string           `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 extension,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 extension,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 extension,omitempty"`
}

// UidRegSourceType was auto-generated from WSDL.
type UidRegSourceType struct {
	Uid                *UidStructureType `xml:"http://www.ech.ch/xmlns/eCH-0108/5 uid,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 uid,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 uid,omitempty"`
	RelationType       string            `xml:"http://www.ech.ch/xmlns/eCH-0108/5 relationType" json:"http://www.ech.ch/xmlns/eCH-0108/5 relationType" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 relationType"`
	RegistrationDate   Date              `xml:"http://www.ech.ch/xmlns/eCH-0108/5 registrationDate" json:"http://www.ech.ch/xmlns/eCH-0108/5 registrationDate" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 registrationDate"`
	RegistrationStatus string            `xml:"http://www.ech.ch/xmlns/eCH-0108/5 registrationStatus" json:"http://www.ech.ch/xmlns/eCH-0108/5 registrationStatus" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 registrationStatus"`
}

// UidStructureType was auto-generated from WSDL.
type UidStructureType struct {
	UidOrganisationIdCategorie UidOrganisationIdCategorieType `xml:"http://www.ech.ch/xmlns/eCH-0097/5 uidOrganisationIdCategorie" json:"http://www.ech.ch/xmlns/eCH-0097/5 uidOrganisationIdCategorie" yaml:"http://www.ech.ch/xmlns/eCH-0097/5 uidOrganisationIdCategorie"`
	UidOrganisationId          *uint                          `xml:"http://www.ech.ch/xmlns/eCH-0097/5 uidOrganisationId,omitempty" json:"http://www.ech.ch/xmlns/eCH-0097/5 uidOrganisationId,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0097/5 uidOrganisationId,omitempty"`
}

// UidregInformationPublicSearchType was auto-generated from WSDL.
type UidregInformationPublicSearchType struct {
	UidregStatusEnterpriseDetail *UidregStatusEnterpriseDetailType `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregStatusEnterpriseDetail,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregStatusEnterpriseDetail,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregStatusEnterpriseDetail,omitempty"`
	UidregUidService             *bool                             `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregUidService,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregUidService,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidregUidService,omitempty"`
}

// UidregInformationType was auto-generated from WSDL.
type UidregInformationType struct {
	UidregStatusEnterpriseDetail *UidregStatusEnterpriseDetailType `xml:"http://www.ech.ch/xmlns/eCH-0108/5 uidregStatusEnterpriseDetail,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 uidregStatusEnterpriseDetail,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 uidregStatusEnterpriseDetail,omitempty"`
	UidregPublicStatus           *UidregPublicStatusType           `xml:"http://www.ech.ch/xmlns/eCH-0108/5 uidregPublicStatus,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 uidregPublicStatus,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 uidregPublicStatus,omitempty"`
	UidregOrganisationType       *UidregOrganisationTypeType       `xml:"http://www.ech.ch/xmlns/eCH-0108/5 uidregOrganisationType,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 uidregOrganisationType,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 uidregOrganisationType,omitempty"`
	UidregLiquidationReason      *UidregLiquidationReasonType      `xml:"http://www.ech.ch/xmlns/eCH-0108/5 uidregLiquidationReason,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 uidregLiquidationReason,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 uidregLiquidationReason,omitempty"`
	UidregSource                 []*UidRegSourceType               `xml:"http://www.ech.ch/xmlns/eCH-0108/5 uidregSource,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 uidregSource,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 uidregSource,omitempty"`
	UidReplacement               *UidStructureType                 `xml:"http://www.ech.ch/xmlns/eCH-0108/5 uidReplacement,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 uidReplacement,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 uidReplacement,omitempty"`
	UidregUidService             *bool                             `xml:"http://www.ech.ch/xmlns/eCH-0108/5 uidregUidService,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 uidregUidService,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 uidregUidService,omitempty"`
	UidregTranslation            *string                           `xml:"http://www.ech.ch/xmlns/eCH-0108/5 uidregTranslation,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 uidregTranslation,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 uidregTranslation,omitempty"`
}

// VatRegisterInformationSearchType was auto-generated from WSDL.
type VatRegisterInformationSearchType struct {
	VatStatus          *VatStatusType      `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatStatus,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatStatus,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatStatus,omitempty"`
	VatEntryStatus     *VatEntryStatusType `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatEntryStatus,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatEntryStatus,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatEntryStatus,omitempty"`
	VatEntryDate       *Date               `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatEntryDate,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatEntryDate,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatEntryDate,omitempty"`
	VatLiquidationDate *Date               `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatLiquidationDate,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatLiquidationDate,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 vatLiquidationDate,omitempty"`
	UidVat             *UidStructureType   `xml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidVat,omitempty" json:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidVat,omitempty" yaml:"http://www.uid.admin.ch/xmlns/uid-wse/5 uidVat,omitempty"`
}

// VatRegisterInformationType was auto-generated from WSDL.
type VatRegisterInformationType struct {
	VatStatus          VatStatusType       `xml:"http://www.ech.ch/xmlns/eCH-0108/5 vatStatus" json:"http://www.ech.ch/xmlns/eCH-0108/5 vatStatus" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 vatStatus"`
	VatEntryStatus     *VatEntryStatusType `xml:"http://www.ech.ch/xmlns/eCH-0108/5 vatEntryStatus,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 vatEntryStatus,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 vatEntryStatus,omitempty"`
	VatEntryDate       *Date               `xml:"http://www.ech.ch/xmlns/eCH-0108/5 vatEntryDate,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 vatEntryDate,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 vatEntryDate,omitempty"`
	VatLiquidationDate *Date               `xml:"http://www.ech.ch/xmlns/eCH-0108/5 vatLiquidationDate,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 vatLiquidationDate,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 vatLiquidationDate,omitempty"`
	UidVat             *UidStructureType   `xml:"http://www.ech.ch/xmlns/eCH-0108/5 uidVat,omitempty" json:"http://www.ech.ch/xmlns/eCH-0108/5 uidVat,omitempty" yaml:"http://www.ech.ch/xmlns/eCH-0108/5 uidVat,omitempty"`
}

// Operation wrapper for GetByUID.
// OperationIPublicServices_GetByUID_InputMessage was auto-generated
// from WSDL.
type OperationIPublicServices_GetByUID_InputMessage struct {
	GetByUID *GetByUID `xml:"GetByUID,omitempty" json:"GetByUID,omitempty" yaml:"GetByUID,omitempty"`
}

// Operation wrapper for GetByUID.
// OperationIPublicServices_GetByUID_OutputMessage was auto-generated
// from WSDL.
type OperationIPublicServices_GetByUID_OutputMessage struct {
	GetByUIDResponse *GetByUIDResponse `xml:"GetByUIDResponse,omitempty" json:"GetByUIDResponse,omitempty" yaml:"GetByUIDResponse,omitempty"`
}

// Operation wrapper for GetOrganisationSample.
// OperationIPublicServices_GetOrganisationSample_InputMessage
// was auto-generated from WSDL.
type OperationIPublicServices_GetOrganisationSample_InputMessage struct {
	GetOrganisationSample *GetOrganisationSample `xml:"GetOrganisationSample,omitempty" json:"GetOrganisationSample,omitempty" yaml:"GetOrganisationSample,omitempty"`
}

// Operation wrapper for GetOrganisationSample.
// OperationIPublicServices_GetOrganisationSample_OutputMessage
// was auto-generated from WSDL.
type OperationIPublicServices_GetOrganisationSample_OutputMessage struct {
	GetOrganisationSampleResponse *GetOrganisationSampleResponse `xml:"GetOrganisationSampleResponse,omitempty" json:"GetOrganisationSampleResponse,omitempty" yaml:"GetOrganisationSampleResponse,omitempty"`
}

// Operation wrapper for Search.
// OperationIPublicServices_Search_InputMessage was auto-generated
// from WSDL.
type OperationIPublicServices_Search_InputMessage struct {
	Search *Search `xml:"Search,omitempty" json:"Search,omitempty" yaml:"Search,omitempty"`
}

// Operation wrapper for Search.
// OperationIPublicServices_Search_OutputMessage was auto-generated
// from WSDL.
type OperationIPublicServices_Search_OutputMessage struct {
	SearchResponse *SearchResponse `xml:"SearchResponse,omitempty" json:"SearchResponse,omitempty" yaml:"SearchResponse,omitempty"`
}

// Operation wrapper for ValidateUID.
// OperationIPublicServices_ValidateUID_InputMessage was auto-generated
// from WSDL.
type OperationIPublicServices_ValidateUID_InputMessage struct {
	ValidateUID *ValidateUID `xml:"ValidateUID,omitempty" json:"ValidateUID,omitempty" yaml:"ValidateUID,omitempty"`
}

// Operation wrapper for ValidateUID.
// OperationIPublicServices_ValidateUID_OutputMessage was auto-generated
// from WSDL.
type OperationIPublicServices_ValidateUID_OutputMessage struct {
	ValidateUIDResponse *ValidateUIDResponse `xml:"ValidateUIDResponse,omitempty" json:"ValidateUIDResponse,omitempty" yaml:"ValidateUIDResponse,omitempty"`
}

// Operation wrapper for ValidateVatNumber.
// OperationIPublicServices_ValidateVatNumber_InputMessage was
// auto-generated from WSDL.
type OperationIPublicServices_ValidateVatNumber_InputMessage struct {
	ValidateVatNumber *ValidateVatNumber `xml:"ValidateVatNumber,omitempty" json:"ValidateVatNumber,omitempty" yaml:"ValidateVatNumber,omitempty"`
}

// Operation wrapper for ValidateVatNumber.
// OperationIPublicServices_ValidateVatNumber_OutputMessage was
// auto-generated from WSDL.
type OperationIPublicServices_ValidateVatNumber_OutputMessage struct {
	ValidateVatNumberResponse *ValidateVatNumberResponse `xml:"ValidateVatNumberResponse,omitempty" json:"ValidateVatNumberResponse,omitempty" yaml:"ValidateVatNumberResponse,omitempty"`
}

// iPublicServices implements the IPublicServices interface.
type iPublicServices struct {
	cli *soap.Client
}

// <summary>             Get the core data (Kernmerkmale) of a
// UID entity by its UID              </summary>
// <param name="uid">UID of requested UID entity</param>
//
//	<returns>The requested UID entity</returns>
func (p *iPublicServices) GetByUID(GetByUID *GetByUID) (*GetByUIDResponse, error) {
	α := struct {
		OperationIPublicServices_GetByUID_InputMessage `xml:"tns:GetByUID"`
	}{
		OperationIPublicServices_GetByUID_InputMessage{
			GetByUID,
		},
	}

	γ := struct {
		OperationIPublicServices_GetByUID_OutputMessage `xml:"GetByUIDResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://www.uid.admin.ch/xmlns/uid-wse/IPublicServices/GetByUID", α, &γ); err != nil {
		return nil, err
	}
	return γ.GetByUIDResponse, nil
}

// <summary>             Returns a data sample to demonstrate
// the structure of eCH-0108:organisationType. The sample contains
// all mapped fields. All data is fictional.              </summary>
//
//	<returns>Data sample</returns>
func (p *iPublicServices) GetOrganisationSample(GetOrganisationSample *GetOrganisationSample) (*GetOrganisationSampleResponse, error) {
	α := struct {
		OperationIPublicServices_GetOrganisationSample_InputMessage `xml:"tns:GetOrganisationSample"`
	}{
		OperationIPublicServices_GetOrganisationSample_InputMessage{
			GetOrganisationSample,
		},
	}

	γ := struct {
		OperationIPublicServices_GetOrganisationSample_OutputMessage `xml:"GetOrganisationSampleResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://www.uid.admin.ch/xmlns/uid-wse/IPublicServices/GetOrganisationSample", α, &γ); err != nil {
		return nil, err
	}
	return γ.GetOrganisationSampleResponse, nil
}

// <summary>             Search for UID-Einheiten
//
//	</summary>             <param name="searchParameters">Search
//
// parameters formated as eCH-0108-3-0f document</param>
//
//	<param name="config">Configuration parameters to customize
//
// search behaviour</param>             <returns>XML-Document
// of type uid-wse</returns>
func (p *iPublicServices) Search(Search *Search) (*SearchResponse, error) {
	α := struct {
		OperationIPublicServices_Search_InputMessage `xml:"tns:Search"`
	}{
		OperationIPublicServices_Search_InputMessage{
			Search,
		},
	}

	γ := struct {
		OperationIPublicServices_Search_OutputMessage `xml:"SearchResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://www.uid.admin.ch/xmlns/uid-wse/IPublicServices/Search", α, &γ); err != nil {
		return nil, err
	}
	return γ.SearchResponse, nil
}

// <summary>             Validate a UID              </summary>
//
//	<param name="uid">UID to validate. Accepted format:
//
// 'CHE123456789' or 'CHE-123.456.789'</param>             <returns>true
// if the UID exists in the UID register</returns>
func (p *iPublicServices) ValidateUID(ValidateUID *ValidateUID) (*ValidateUIDResponse, error) {
	α := struct {
		OperationIPublicServices_ValidateUID_InputMessage `xml:"tns:ValidateUID"`
	}{
		OperationIPublicServices_ValidateUID_InputMessage{
			ValidateUID,
		},
	}

	γ := struct {
		OperationIPublicServices_ValidateUID_OutputMessage `xml:"ValidateUIDResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://www.uid.admin.ch/xmlns/uid-wse/IPublicServices/ValidateUID", α, &γ); err != nil {
		return nil, err
	}
	return γ.ValidateUIDResponse, nil
}

// <summary>             Validate a VatNumber              </summary>
//
//	<param name="vatNumber">VAT number to validate</param>
//	<returns>true if exists</returns>
func (p *iPublicServices) ValidateVatNumber(ValidateVatNumber *ValidateVatNumber) (*ValidateVatNumberResponse, error) {
	α := struct {
		OperationIPublicServices_ValidateVatNumber_InputMessage `xml:"tns:ValidateVatNumber"`
	}{
		OperationIPublicServices_ValidateVatNumber_InputMessage{
			ValidateVatNumber,
		},
	}

	γ := struct {
		OperationIPublicServices_ValidateVatNumber_OutputMessage `xml:"ValidateVatNumberResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://www.uid.admin.ch/xmlns/uid-wse/IPublicServices/ValidateVatNumber", α, &γ); err != nil {
		return nil, err
	}
	return γ.ValidateVatNumberResponse, nil
}
